WITH AGGREGATED_DATA AS (
    SELECT
        STORE,
        SUM(WEEKLY_SALES) AS TOTAL_WEEKLY_SALES,
        COUNT(DISTINCT DATE) AS WEEKS_ACTIVE
    FROM {{ ref('cleaned_sales') }}
    GROUP BY STORE
)
SELECT * FROM AGGREGATED_DATA
